// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WMS.Backend.API.Data;

#nullable disable

namespace WMS.Backend.API.Migrations
{
    [DbContext(typeof(WMSDbContext))]
    partial class WMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WMS.Backend.API.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("AuditId");

                    b.HasIndex("ChangedDate");

                    b.HasIndex("TableName", "RecordId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("WMS.Backend.API.Models.CustomerOrder", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CompleteDeliveryRequired")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.HasIndex("Status");

                    b.HasIndex("Priority", "OrderDate");

                    b.ToTable("CustomerOrders");
                });

            modelBuilder.Entity("WMS.Backend.API.Models.OrderLineItem", b =>
                {
                    b.Property<string>("LineItemId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("AllocatedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("LineItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductNumber");

                    b.HasIndex("Status");

                    b.ToTable("OrderLineItems");
                });

            modelBuilder.Entity("WMS.Backend.API.Models.SKU", b =>
                {
                    b.Property<string>("SkuId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocationLocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarehouseLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("SkuId");

                    b.HasIndex("ProductNumber");

                    b.HasIndex("WarehouseLocation");

                    b.HasIndex("ProductNumber", "AvailableQuantity", "IsLocationLocked");

                    b.ToTable("SKUs", t =>
                        {
                            t.HasCheckConstraint("CK_SKU_AvailableQuantity", "AvailableQuantity <= TotalQuantity");
                        });

                    b.HasData(
                        new
                        {
                            SkuId = "SKU001",
                            AvailableQuantity = 100,
                            CreatedDate = new DateTime(2026, 1, 27, 5, 2, 48, 420, DateTimeKind.Utc).AddTicks(4096),
                            IsLocationLocked = false,
                            LastModifiedDate = new DateTime(2026, 1, 27, 5, 2, 48, 420, DateTimeKind.Utc).AddTicks(4097),
                            ProductNumber = "P001",
                            TotalQuantity = 100,
                            WarehouseLocation = "A-01-01"
                        },
                        new
                        {
                            SkuId = "SKU002",
                            AvailableQuantity = 50,
                            CreatedDate = new DateTime(2026, 1, 27, 5, 2, 48, 420, DateTimeKind.Utc).AddTicks(4099),
                            IsLocationLocked = false,
                            LastModifiedDate = new DateTime(2026, 1, 27, 5, 2, 48, 420, DateTimeKind.Utc).AddTicks(4099),
                            ProductNumber = "P001",
                            TotalQuantity = 50,
                            WarehouseLocation = "A-01-02"
                        },
                        new
                        {
                            SkuId = "SKU003",
                            AvailableQuantity = 75,
                            CreatedDate = new DateTime(2026, 1, 27, 5, 2, 48, 420, DateTimeKind.Utc).AddTicks(4101),
                            IsLocationLocked = false,
                            LastModifiedDate = new DateTime(2026, 1, 27, 5, 2, 48, 420, DateTimeKind.Utc).AddTicks(4102),
                            ProductNumber = "P002",
                            TotalQuantity = 75,
                            WarehouseLocation = "B-02-01"
                        },
                        new
                        {
                            SkuId = "SKU004",
                            AvailableQuantity = 25,
                            CreatedDate = new DateTime(2026, 1, 27, 5, 2, 48, 420, DateTimeKind.Utc).AddTicks(4104),
                            IsLocationLocked = true,
                            LastModifiedDate = new DateTime(2026, 1, 27, 5, 2, 48, 420, DateTimeKind.Utc).AddTicks(4104),
                            ProductNumber = "P002",
                            TotalQuantity = 25,
                            WarehouseLocation = "B-02-02"
                        },
                        new
                        {
                            SkuId = "SKU005",
                            AvailableQuantity = 200,
                            CreatedDate = new DateTime(2026, 1, 27, 5, 2, 48, 420, DateTimeKind.Utc).AddTicks(4106),
                            IsLocationLocked = false,
                            LastModifiedDate = new DateTime(2026, 1, 27, 5, 2, 48, 420, DateTimeKind.Utc).AddTicks(4106),
                            ProductNumber = "P003",
                            TotalQuantity = 200,
                            WarehouseLocation = "C-03-01"
                        });
                });

            modelBuilder.Entity("WMS.Backend.API.Models.StockAllocation", b =>
                {
                    b.Property<string>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("AllocatedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AllocationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LineItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkuId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("AllocationId");

                    b.HasIndex("LineItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SkuId");

                    b.HasIndex("OrderId", "LineItemId");

                    b.ToTable("StockAllocations");
                });

            modelBuilder.Entity("WMS.Backend.API.Models.OrderLineItem", b =>
                {
                    b.HasOne("WMS.Backend.API.Models.CustomerOrder", "Order")
                        .WithMany("LineItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WMS.Backend.API.Models.StockAllocation", b =>
                {
                    b.HasOne("WMS.Backend.API.Models.OrderLineItem", "LineItem")
                        .WithMany("Allocations")
                        .HasForeignKey("LineItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMS.Backend.API.Models.CustomerOrder", "Order")
                        .WithMany("Allocations")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMS.Backend.API.Models.SKU", "SKU")
                        .WithMany("Allocations")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LineItem");

                    b.Navigation("Order");

                    b.Navigation("SKU");
                });

            modelBuilder.Entity("WMS.Backend.API.Models.CustomerOrder", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("WMS.Backend.API.Models.OrderLineItem", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("WMS.Backend.API.Models.SKU", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
